spring.application.name=bank-wallet
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
exchangerates.api.access-key=51af7e7e302febc8fbf61b19ecd118be
exchangerates.api.base-url=https://api.exchangeratesapi.io/v1
